### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by konegen** [Xraydylan/Arducam_OV2640_Python_Package_Raspberry_Pi_Pico#1]
- Name:
Self-explanatory names are best when choosing a name for a repository.

- One-liner:
In a one-liner, the project should be briefly described to give a general overview of its function and application area.
It should answer the question "What problem does it solve?"

- Description:
After briefly describing the repository in one sentence, it should then be explained in more detail. The following aspects can be addressed here:
    - Why was the application developed?
    - What does the application do?
    - What technology was used?
    - What functions are to be implemented in the future?

- Installation:
In order to be able to execute the application of the repository, further modules are usually required, which can be installed with PyPi, for example.
At this point, these modules, as well as their version, should be presented. This can be done, for example, by providing a "requirements" file in which 
all required modules, as well as the version used, are listed.

- Usage:
In order to use the repository you should not have to look at the API and source code of the project. Instead, the README should show the repository in action.
There should also be a short tutorial explaining how to use the tool.
For a better visual representation, screenshots or images should also be included, e.g. showing the tool in action.

- License:
The last section of the README is usually the license. The license defines how the repository can be used by other developers.

**Comment by Xraydylan** [comment]
I still need to write the Usage section. 
But so far is there anything that can be further improved?
