### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by euhidaman** [Xraydylan/Arducam_OV2640_Python_Package_Raspberry_Pi_Pico#5]
I am trying to emulate this on my Windows Machine.

I have connected everything, according to the given diagram, and followed all the steps, present in this README[!https://github.com/Xraydylan/Arducam-OV2640-Pico-Package/blob/main/Pico/README.md] file.
Can you please tell me, what should I do next? What file should I run next?

The official code present in the documentation is giving me errors. So, I would really like your help.

**Comment by Xraydylan** [comment]
What error messages do you get and what part are you currently struggling with?

Is it the setup of the Pico or is it the Python code to receive the images on the PC?

**Comment by euhidaman** [comment]
I tried following the main documentation, and I got this error : https://github.com/ArduCAM/PICO_SPI_CAM/issues/5#issue-1074143673

So, I tried to follow your code. And, now I am struggling with knowing how to receive the images on my PC.

I would really like your help. Thank You!

**Comment by Xraydylan** [comment]
Hmmm
I as far as I could find out the error you are having with the pico has something to do with the I2C bus to the Arducam.
Unfortunately I don't have my original hardware anymore to properly test it.

But I have 2 things you could try:
- Getting a newer [Circuitpython](https://circuitpython.org/board/raspberry_pi_pico/) version
- Checking that the Arduicam is properly connected and powered

**Comment by euhidaman** [comment]
I am running `CircuitPython 7.3.3` and am getting this error:
![err-pico](https://user-images.githubusercontent.com/65843257/213968364-47d3b6b5-c97a-47e7-bc34-249195f4fbd3.png)

Is there any way to fix this error? Any help will be highly appreciated!

**Comment by euhidaman** [comment]
Okay, 

> Hmmm I as far as I could find out the error you are having with the pico has something to do with the I2C bus to the Arducam. Unfortunately I don't have my original hardware anymore to properly test it.
> 
> But I have 2 things you could try:
> 
> * Getting a newer [Circuitpython](https://circuitpython.org/board/raspberry_pi_pico/) version
> * Checking that the Arduicam is properly connected and powered

I would like to tell that, My issue was resolved. I had connected one wire in a wrong manner. I would also like to thank you for your help!
